In [2]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('sample_hydroponic_data (1).csv')
df.head()

,id,timestamp,flowrate,distance,moisture1,moisture2,moisture3,moisture4,moisture5,moisture6,...,humidity_bawah,ph,tds,total_liters,avg_moisture,avg_temperature,avg_humidity,pump_status,light_status,automation_status
0,019d0baf-28b4-7121-84c0-9c18a6b8a7bc,2026-01-01T00:00:00Z,2.88,12.84,34,45,23,78,81,63,...,49.55,6.57,659.44,134.65,54.00,25.75,66.94,True,False,True
1,019d0baf-28b4-7121-84c0-9c19f6e7dd72,2026-01-01T01:00:00Z,1.35,13.34,61,91,74,89,79,83,...,73.96,7.40,655.21,81.87,79.50,26.33,65.85,False,False,False
2,019d0baf-28b4-7121-84c0-9c1a7db40ec8,2026-01-01T02:00:00Z,2.00,6.83,59,20,36,89,73,81,...,49.79,6.28,332.99,125.15,59.67,20.52,62.92,False,False,False
3,019d0baf-28b4-7121-84c0-9c1b724239ad,2026-01-01T03:00:00Z,1.77,5.68,71,83,92,83,93,71,...,47.14,6.46,542.42,68.02,82.17,20.07,67.22,False,True,True
4,019d0baf-28b4-7121-84c0-9c1c5139eaac,2026-01-01T04:00:00Z,2.07,12.80,32,68,50,92,99,60,...,56.51,6.56,551.30,144.46,66.83,22.40,51.29,False,True,False

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  str
 1   timestamp          10000 non-null  str
 2   flowrate           10000 non-null  float64
 3   distance           10000 non-null  float64
 4   moisture1          10000 non-null  int64
 5   moisture2          10000 non-null  int64
 6   moisture3          10000 non-null  int64
 7   moisture4          10000 non-null  int64
 8   moisture5          10000 non-null  int64
 9   moisture6          10000 non-null  int64
 10  temperature_atas   10000 non-null  float64
 11  temperature_bawah  10000 non-null  float64
 12  humidity_atas      10000 non-null  float64
 13  humidity_bawah     10000 non-null  float64
 14  ph                 10000 non-null  float64
 15  tds                10000 non-null  float64
 16  total_liters       10000 non-null  float64
 17  avg_moisture       10000 non-null  float64
 18  avg_temperature    10000 non-null  float64
 19  avg_humidity       10000 non-null  float64
 20  pump_status        10000 non-null  bool
 21  light_status       10000 non-null  bool
 22  automation_status  10000 non-null  bool
dtypes: bool(3), float64(12), int64(6), str(2)
memory usage: 1.6 MB

In [13]:
df_tes = pd.read_csv('hydroponic_data.csv')
df_tes

,Id,Timestamp,Moisture 1 (%),Moisture 2 (%),Moisture 3 (%),Moisture 4 (%),Moisture 5 (%),Moisture 6 (%),Flow Rate (L/m),Total Liters (L),Distance (m),pH,TDS (ppm),Temp Atas (°C),Temp Bawah (°C),Hum Atas (%),Hum Bawah (%),Pump Status,Light Status,Automation Status
0,019d0baf-28b4-7121-84c0-9c18a6b8a7bc,2026-01-01T00:00:00.000Z,34,45,23,78,81,63,2.88,134.65,12.84,6.57,659.44,29.34,21.87,78.19,49.55,ON,OFF,ON
1,019d0baf-28b4-7121-84c0-9c19f6e7dd72,2026-01-01T01:00:00.000Z,61,91,74,89,79,83,1.35,81.87,13.34,7.40,655.21,29.80,21.40,52.22,73.96,OFF,OFF,OFF
2,019d0baf-28b4-7121-84c0-9c1a7db40ec8,2026-01-01T02:00:00.000Z,59,20,36,89,73,81,2.00,125.15,6.83,6.28,332.99,22.19,21.84,78.31,49.79,OFF,OFF,OFF
3,019d0baf-28b4-7121-84c0-9c1b724239ad,2026-01-01T03:00:00.000Z,71,83,92,83,93,71,1.77,68.02,5.68,6.46,542.42,28.62,16.48,51.91,47.14,OFF,ON,ON
4,019d0baf-28b4-7121-84c0-9c1c5139eaac,2026-01-01T04:00:00.000Z,32,68,50,92,99,60,2.07,144.46,12.80,6.56,551.30,25.83,23.60,59.55,56.51,OFF,ON,OFF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,019d0baf-2a7f-7678-a9f4-d408405d1d82,2027-02-21T11:00:00.000Z,96,61,29,80,66,70,0.75,93.69,13.51,7.28,594.77,27.37,22.03,57.89,46.40,ON,OFF,OFF
9996,019d0baf-2a7f-7678-a9f4-d4091ec184a4,2027-02-21T12:00:00.000Z,97,59,98,29,26,48,2.98,53.75,13.13,6.52,361.96,22.66,24.29,53.44,73.70,OFF,OFF,OFF
9997,019d0baf-2a7f-7678-a9f4-d40a588636c7,2027-02-21T13:00:00.000Z,42,45,46,45,74,100,1.41,120.08,12.94,6.99,535.70,23.21,19.71,60.96,53.65,OFF,OFF,OFF
9998,019d0baf-2a7f-7678-a9f4-d40b9456011d,2027-02-21T14:00:00.000Z,51,93,44,90,42,62,2.61,103.56,10.09,6.89,608.45,21.58,16.56,73.60,55.35,ON,ON,OFF
9999,019d0baf-2a7f-7678-a9f4-d40c393723e5,2027-02-21T15:00:00.000Z,58,55,37,24,53,54,0.99,128.67,10.26,6.35,595.39,25.50,15.32,53.21,69.49,OFF,ON,ON

In [12]:
df_tes.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  str
 1   timestamp          10000 non-null  str
 2   flowrate           10000 non-null  float64
 3   distance           10000 non-null  float64
 4   moisture1          10000 non-null  int64
 5   moisture2          10000 non-null  int64
 6   moisture3          10000 non-null  int64
 7   moisture4          10000 non-null  int64
 8   moisture5          10000 non-null  int64
 9   moisture6          10000 non-null  int64
 10  temperature_atas   10000 non-null  float64
 11  temperature_bawah  10000 non-null  float64
 12  humidity_atas      10000 non-null  float64
 13  humidity_bawah     10000 non-null  float64
 14  ph                 10000 non-null  float64
 15  tds                10000 non-null  float64
 16  total_liters       10000 non-null  float64
 17  avg_moisture       10000 non-null  float64
 18  avg_temperature    10000 non-null  float64
 19  avg_humidity       10000 non-null  float64
 20  pump_status        10000 non-null  bool
 21  light_status       10000 non-null  bool
 22  automation_status  10000 non-null  bool
dtypes: bool(3), float64(12), int64(6), str(2)
memory usage: 1.6 MB

In [15]:
df_data_sensor = pd.read_csv('hydroponic_data_sensor.csv')
df_data_sensor

,Id,Timestamp,Moisture 1 (%),Moisture 2 (%),Moisture 3 (%),Moisture 4 (%),Moisture 5 (%),Moisture 6 (%),Flow Rate (L/m),Total Liters (L),Distance (m)
0,019d0baf-28b4-7121-84c0-9c18a6b8a7bc,2026-01-01T00:00:00.000Z,34,45,23,78,81,63,2.88,134.65,12.84
1,019d0baf-28b4-7121-84c0-9c19f6e7dd72,2026-01-01T01:00:00.000Z,61,91,74,89,79,83,1.35,81.87,13.34
2,019d0baf-28b4-7121-84c0-9c1a7db40ec8,2026-01-01T02:00:00.000Z,59,20,36,89,73,81,2.00,125.15,6.83
3,019d0baf-28b4-7121-84c0-9c1b724239ad,2026-01-01T03:00:00.000Z,71,83,92,83,93,71,1.77,68.02,5.68
4,019d0baf-28b4-7121-84c0-9c1c5139eaac,2026-01-01T04:00:00.000Z,32,68,50,92,99,60,2.07,144.46,12.80
...,...,...,...,...,...,...,...,...,...,...,...
9995,019d0baf-2a7f-7678-a9f4-d408405d1d82,2027-02-21T11:00:00.000Z,96,61,29,80,66,70,0.75,93.69,13.51
9996,019d0baf-2a7f-7678-a9f4-d4091ec184a4,2027-02-21T12:00:00.000Z,97,59,98,29,26,48,2.98,53.75,13.13
9997,019d0baf-2a7f-7678-a9f4-d40a588636c7,2027-02-21T13:00:00.000Z,42,45,46,45,74,100,1.41,120.08,12.94
9998,019d0baf-2a7f-7678-a9f4-d40b9456011d,2027-02-21T14:00:00.000Z,51,93,44,90,42,62,2.61,103.56,10.09
9999,019d0baf-2a7f-7678-a9f4-d40c393723e5,2027-02-21T15:00:00.000Z,58,55,37,24,53,54,0.99,128.67,10.26

In [16]:
df_data_environment = pd.read_csv('hydroponic_data_environment.csv')
df_data_environment

,Id,Timestamp,pH,TDS (ppm),Temp Atas (°C),Temp Bawah (°C),Hum Atas (%),Hum Bawah (%)
0,019d0baf-28b4-7121-84c0-9c18a6b8a7bc,2026-01-01T00:00:00.000Z,6.57,659.44,29.34,21.87,78.19,49.55
1,019d0baf-28b4-7121-84c0-9c19f6e7dd72,2026-01-01T01:00:00.000Z,7.40,655.21,29.80,21.40,52.22,73.96
2,019d0baf-28b4-7121-84c0-9c1a7db40ec8,2026-01-01T02:00:00.000Z,6.28,332.99,22.19,21.84,78.31,49.79
3,019d0baf-28b4-7121-84c0-9c1b724239ad,2026-01-01T03:00:00.000Z,6.46,542.42,28.62,16.48,51.91,47.14
4,019d0baf-28b4-7121-84c0-9c1c5139eaac,2026-01-01T04:00:00.000Z,6.56,551.30,25.83,23.60,59.55,56.51
...,...,...,...,...,...,...,...,...
9995,019d0baf-2a7f-7678-a9f4-d408405d1d82,2027-02-21T11:00:00.000Z,7.28,594.77,27.37,22.03,57.89,46.40
9996,019d0baf-2a7f-7678-a9f4-d4091ec184a4,2027-02-21T12:00:00.000Z,6.52,361.96,22.66,24.29,53.44,73.70
9997,019d0baf-2a7f-7678-a9f4-d40a588636c7,2027-02-21T13:00:00.000Z,6.99,535.70,23.21,19.71,60.96,53.65
9998,019d0baf-2a7f-7678-a9f4-d40b9456011d,2027-02-21T14:00:00.000Z,6.89,608.45,21.58,16.56,73.60,55.35
9999,019d0baf-2a7f-7678-a9f4-d40c393723e5,2027-02-21T15:00:00.000Z,6.35,595.39,25.50,15.32,53.21,69.49

In [17]:
df_data_actuator = pd.read_csv('hydroponic_data_actuator.csv')
df_data_actuator

,Id,Timestamp,Pump Status,Light Status,Automation Status
0,019d0baf-28b4-7121-84c0-9c18a6b8a7bc,2026-01-01T00:00:00.000Z,ON,OFF,ON
1,019d0baf-28b4-7121-84c0-9c19f6e7dd72,2026-01-01T01:00:00.000Z,OFF,OFF,OFF
2,019d0baf-28b4-7121-84c0-9c1a7db40ec8,2026-01-01T02:00:00.000Z,OFF,OFF,OFF
3,019d0baf-28b4-7121-84c0-9c1b724239ad,2026-01-01T03:00:00.000Z,OFF,ON,ON
4,019d0baf-28b4-7121-84c0-9c1c5139eaac,2026-01-01T04:00:00.000Z,OFF,ON,OFF
...,...,...,...,...,...
9995,019d0baf-2a7f-7678-a9f4-d408405d1d82,2027-02-21T11:00:00.000Z,ON,OFF,OFF
9996,019d0baf-2a7f-7678-a9f4-d4091ec184a4,2027-02-21T12:00:00.000Z,OFF,OFF,OFF
9997,019d0baf-2a7f-7678-a9f4-d40a588636c7,2027-02-21T13:00:00.000Z,OFF,OFF,OFF
9998,019d0baf-2a7f-7678-a9f4-d40b9456011d,2027-02-21T14:00:00.000Z,ON,ON,OFF
9999,019d0baf-2a7f-7678-a9f4-d40c393723e5,2027-02-21T15:00:00.000Z,OFF,ON,ON